
name = "dqmc"


[build]
auto-executables = true
auto-tests = true
auto-examples = true
link=["blas", "lapack"]


[install]
library = false

[[executable]]
name="main"
source-dir="dqmc"
main="main.f90"

